version: '3.8'

services:
  recommender-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
    - .env
    volumes:
      - ./artifacts:/app/artifacts  # Persist downloaded artifacts
    environment:
      - PYTHONUNBUFFERED=1
    command: ["bash", "-c", "./download_artifacts.sh && uvicorn app.app:app --host 0.0.0.0 --port 8000"]
    restart: unless-stopped